CREATE DATABASE db_videos;

CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL, CHECK (name <> ''),
    phone TEXT,
    email TEXT NOT NULL, CHECK (email <> ''),
    password TEXT NOT NULL, CHECK (email <> ''),
    sign_up_date DATE
);

CREATE TABLE IF NOT EXISTS videos(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL, CHECK (title <> ''),
    url TEXT NOT NULL, CHECK (url <> ''),
    qualification INTEGER,
    description TEXT,
    user_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS liked_videos(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    video_id INTEGER NOT NULL REFERENCES videos(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    liked BOOLEAN NOT NULL,
    comments TEXT,
    recommended BOOLEAN
);